var annotated_dup =
[
    [ "dispenso", null, [
      [ "AsyncRequest", "classdispenso_1_1_async_request.html", "classdispenso_1_1_async_request" ],
      [ "BiPropNode", "classdispenso_1_1_bi_prop_node.html", "classdispenso_1_1_bi_prop_node" ],
      [ "CacheAligned", "classdispenso_1_1_cache_aligned.html", "classdispenso_1_1_cache_aligned" ],
      [ "CacheGroup", "structdispenso_1_1_cache_group.html", "structdispenso_1_1_cache_group" ],
      [ "ChaseLevDeque", "classdispenso_1_1_chase_lev_deque.html", "classdispenso_1_1_chase_lev_deque" ],
      [ "CompletionEvent", "classdispenso_1_1_completion_event.html", "classdispenso_1_1_completion_event" ],
      [ "ConcurrentObjectArena", "structdispenso_1_1_concurrent_object_arena.html", "structdispenso_1_1_concurrent_object_arena" ],
      [ "ConcurrentTaskSet", "classdispenso_1_1_concurrent_task_set.html", "classdispenso_1_1_concurrent_task_set" ],
      [ "ConcurrentTaskSetExecutor", "classdispenso_1_1_concurrent_task_set_executor.html", null ],
      [ "ConcurrentVector", "classdispenso_1_1_concurrent_vector.html", "classdispenso_1_1_concurrent_vector" ],
      [ "CpuSet", "classdispenso_1_1_cpu_set.html", "classdispenso_1_1_cpu_set" ],
      [ "DefaultConcurrentVectorSizeTraits", "structdispenso_1_1_default_concurrent_vector_size_traits.html", null ],
      [ "DefaultConcurrentVectorTraits", "structdispenso_1_1_default_concurrent_vector_traits.html", null ],
      [ "DistributedRWLock", "classdispenso_1_1_distributed_r_w_lock.html", "classdispenso_1_1_distributed_r_w_lock" ],
      [ "ForEachOptions", "structdispenso_1_1_for_each_options.html", "structdispenso_1_1_for_each_options" ],
      [ "ForwardPropagator", "classdispenso_1_1_forward_propagator.html", null ],
      [ "Future", "classdispenso_1_1_future.html", "classdispenso_1_1_future" ],
      [ "Future< Result & >", "classdispenso_1_1_future_3_01_result_01_6_01_4.html", "classdispenso_1_1_future_3_01_result_01_6_01_4" ],
      [ "Future< void >", "classdispenso_1_1_future_3_01void_01_4.html", "classdispenso_1_1_future_3_01void_01_4" ],
      [ "GraphT", "classdispenso_1_1_graph_t.html", "classdispenso_1_1_graph_t" ],
      [ "GroupWakeState", "structdispenso_1_1_group_wake_state.html", null ],
      [ "ImmediateInvoker", "classdispenso_1_1_immediate_invoker.html", "classdispenso_1_1_immediate_invoker" ],
      [ "Latch", "classdispenso_1_1_latch.html", "classdispenso_1_1_latch" ],
      [ "MpmcRingBuffer", "classdispenso_1_1_mpmc_ring_buffer.html", "classdispenso_1_1_mpmc_ring_buffer" ],
      [ "NewThreadInvoker", "classdispenso_1_1_new_thread_invoker.html", "classdispenso_1_1_new_thread_invoker" ],
      [ "Node", "classdispenso_1_1_node.html", "classdispenso_1_1_node" ],
      [ "OnceFunction", "classdispenso_1_1_once_function.html", "classdispenso_1_1_once_function" ],
      [ "ParallelForExecutor", "classdispenso_1_1_parallel_for_executor.html", null ],
      [ "ParForOptions", "structdispenso_1_1_par_for_options.html", "structdispenso_1_1_par_for_options" ],
      [ "PoolAllocatorT", "classdispenso_1_1_pool_allocator_t.html", "classdispenso_1_1_pool_allocator_t" ],
      [ "PoolWakeState", "classdispenso_1_1_pool_wake_state.html", "classdispenso_1_1_pool_wake_state" ],
      [ "ReserveTagS", "structdispenso_1_1_reserve_tag_s.html", null ],
      [ "Resource", "classdispenso_1_1_resource.html", "classdispenso_1_1_resource" ],
      [ "ResourcePool", "classdispenso_1_1_resource_pool.html", "classdispenso_1_1_resource_pool" ],
      [ "RWLock", "classdispenso_1_1_r_w_lock.html", null ],
      [ "SingleThreadExecutor", "classdispenso_1_1_single_thread_executor.html", null ],
      [ "SmallVector", "classdispenso_1_1_small_vector.html", "classdispenso_1_1_small_vector" ],
      [ "SPSCRingBuffer", "classdispenso_1_1_s_p_s_c_ring_buffer.html", "classdispenso_1_1_s_p_s_c_ring_buffer" ],
      [ "SubgraphT", "classdispenso_1_1_subgraph_t.html", "classdispenso_1_1_subgraph_t" ],
      [ "TaskSet", "classdispenso_1_1_task_set.html", "classdispenso_1_1_task_set" ],
      [ "ThreadGroup", "structdispenso_1_1_thread_group.html", "structdispenso_1_1_thread_group" ],
      [ "ThreadPool", "classdispenso_1_1_thread_pool.html", "classdispenso_1_1_thread_pool" ],
      [ "TimedTask", "classdispenso_1_1_timed_task.html", "classdispenso_1_1_timed_task" ],
      [ "TimedTaskScheduler", "classdispenso_1_1_timed_task_scheduler.html", "classdispenso_1_1_timed_task_scheduler" ],
      [ "UnalignedRWLock", "classdispenso_1_1_unaligned_r_w_lock.html", null ],
      [ "WaiterBlock", "structdispenso_1_1_waiter_block.html", null ]
    ] ]
];