name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-tests:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,  macOS-latest, windows-latest]
    env:
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Installing
        run: |
          sudo apt-get update && sudo apt-get install -y gcc g++ cmake

      - name: Configuring
        run: |
          mkdir build && cd build && cmake .. -DDISPENSO_BUILD_TESTS=ON
        shell: bash
      - name: Build
        working-directory: ./build
        run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
              cmake --build . --config Release
           else
              cmake --build . -- -j$(nproc)
           fi
        shell: bash

      - name: Running Unit Tests
        working-directory: ./build
        run: |
          ctest -LE flaky --build-config Release
